name       : libopusenc
version    : 0.2.1
release    : 1
source     :
    - https://archive.mozilla.org/pub/opus/libopusenc-0.2.1.tar.gz : 8298db61a8d3d63e41c1a80705baa8ce9ff3f50452ea7ec1c19a564fe106cbb9
license    : BSD-3-Clause
component  : programming.library
summary    : A library that provides an easy way to encode Ogg Opus files
description: |
    High-level API for encoding .opus files
builddeps  :
    - pkgconfig(opus)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
